version: 2
jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck:stable
    steps:
      - checkout
      - run:
          name: ShellCheck
          command: for file in $(find $CIRCLE_WORKING_DIRECTORY -type f); do shellcheck --format=gcc $file; done;

workflows:
  version: 2
  test:
    jobs:
      - shellcheck