version: 2
jobs:
  shellcheck:
    docker:
      - image: debian:stable-slim
    steps:
      - checkout
      - run:
          name: Update
          command: apt update
      - run:
          name: Install
          command: apt install -y shellcheck
      - run:
          name: ShellCheck
          command: shellcheck super_shell.sh

workflows:
  version: 2
  test:
    jobs:
      - shellcheck