version: 2
jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck:stable
    steps:
      - checkout
      - run:
          name: ShellCheck
          command: $CIRCLE_WORKING_DIRECTORY/super_shell.sh

workflows:
  version: 2
  test:
    jobs:
      - shellcheck