version: 2
jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck:stable
    steps:
      - checkout
      - run:
          name: ShellCheck
          command: for file in $(find . -type f); do shellcheck --format=gcc $file; done;